library(rmarkdown)
library(dada2)
library(ggplot2)
library(knitr)
library(kableExtra)
library(reshape2)

informeFinal <- function() {
  
  timestamp <- format(Sys.time(), "%Y-%m-%d_%H-%M")
  directorio_salida <- file.path("OUTPUT/REPORT", paste0("InformeFinal_", timestamp))
  dir.create(directorio_salida, recursive = TRUE, showWarnings = FALSE)
  
  cat(sprintf("Generando informe Rmarkdown"))
  archivoRmd <- construirRmd(directorio_salida, timestamp)
  
  rmarkdown::render(archivoRmd, quiet = TRUE, output_file = "informe_final.html",
                    knit_root_dir = getwd())
  browseURL(file.path(directorio_salida, "informe_final.html"))
  
  cat("Informe disponible en:")
  return(directorio_salida)
}


construirRmd <- function(directorio_salida, timestamp) {
  
  archivoRmd <- file.path(directorio_salida, "informe_final.Rmd")
  
  contenido <- c(
    '---',
    'title: "Análisis de Microbioma Intestinal en Esclerosis Múltiple"',
    'subtitle: "Pipeline DADA2 — Informe de Resultados"',
    paste0('date: "', timestamp, '"'),
    'output:',
    '  html_document:',
    '    theme: flatly',
    '    highlight: tango',
    '    toc: true',
    '    toc_depth: 3',
    '    toc_float:',
    '      collapsed: false',
    '      smooth_scroll: true',
    '    number_sections: true',
    '    df_print: paged',
    '    fig_width: 9',
    '    fig_height: 5',
    '---',
    '',
    '```{r setup, include=FALSE}',
    'knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE, fig.align = "center")',
    'library(dada2)',
    'library(ggplot2)',
    'library(knitr)',
    'library(kableExtra)',
    'library(reshape2)',
    '```',
    '',
    '---',
    '',
    '## Carga de Resultados',
    '',
    '```{r cargar-rds}',
    'seqtab_path  <- "OUTPUT/RDS/seqtab.Rds"',
    'sinquim_path <- "OUTPUT/RDS/tabSinQuim.Rds"',
    '',
    'seqtab_ok  <- file.exists(seqtab_path)',
    'sinquim_ok <- file.exists(sinquim_path)',
    '',
    'if (seqtab_ok)  seqtab     <- readRDS(seqtab_path)',
    'if (sinquim_ok) tabSinQuim <- readRDS(sinquim_path)',
    '',
    'taxa_files <- list.files("OUTPUT/RDS", pattern = "\\\\.Rds$", full.names = TRUE)',
    'taxa_files <- taxa_files[!grepl("seqtab|tabSinQuim|union|errores", taxa_files)]',
    'taxa_ok    <- length(taxa_files) > 0',
    'if (taxa_ok) taxa <- readRDS(taxa_files[1])',
    '```',
    '',
    '---',
    '',
    '## Tabla de Secuencias',
    '',
    '### Dimensiones',
    '',
    '```{r seqtab-dim}',
    'if (seqtab_ok) {',
    '  n_muestras <- nrow(seqtab)',
    '  n_asv      <- ncol(seqtab)',
    '  data.frame(',
    '    Métrica = c("Muestras", "ASVs únicos"),',
    '    Valor   = c(n_muestras, n_asv)',
    '  ) |>',
    '    kable(caption = "Dimensiones de la tabla de secuencias (antes de eliminar quimeras)") |>',
    '    kable_styling(bootstrap_options = c("striped", "hover", "condensed"), full_width = FALSE)',
    '} else {',
    '  cat("`seqtab.Rds` no encontrado. Ejecuta primero `procesarSecuencias()`.")',
    '}',
    '```',
    '',
    '### Distribución de longitudes de amplicon',
    '',
    '```{r longitud-amplicon}',
    'if (seqtab_ok) {',
    '  len_df <- as.data.frame(table(nchar(getSequences(seqtab))))',
    '  colnames(len_df) <- c("Longitud_pb", "Numero_ASVs")',
    '  len_df$Longitud_pb <- as.numeric(as.character(len_df$Longitud_pb))',
    '  ggplot(len_df, aes(x = Longitud_pb, y = Numero_ASVs)) +',
    '    geom_col(fill = "#2c7bb6", color = "white", width = 0.8) +',
    '    labs(title = "Distribución de longitudes de amplicon",',
    '         x = "Longitud (pb)", y = "Número de ASVs") +',
    '    theme_minimal(base_size = 13) +',
    '    theme(plot.title = element_text(face = "bold"))',
    '}',
    '```',
    '',
    '---',
    '',
    '## Eliminación de Quimeras',
    '',
    '```{r quimeras}',
    'if (seqtab_ok && sinquim_ok) {',
    '  reads_pre  <- sum(seqtab)',
    '  reads_post <- sum(tabSinQuim)',
    '  asvs_pre   <- ncol(seqtab)',
    '  asvs_post  <- ncol(tabSinQuim)',
    '  pct_reads  <- round(reads_post / reads_pre * 100, 2)',
    '  pct_asvs   <- round(asvs_post  / asvs_pre  * 100, 2)',
    '  data.frame(',
    '    Métrica = c("Lecturas totales (pre)", "Lecturas retenidas (post)",',
    '                "% lecturas retenidas", "ASVs (pre)",',
    '                "ASVs retenidos (post)", "% ASVs retenidos"),',
    '    Valor   = c(format(reads_pre,  big.mark = "."),',
    '                format(reads_post, big.mark = "."),',
    '                paste0(pct_reads, " %"),',
    '                asvs_pre, asvs_post,',
    '                paste0(pct_asvs, " %"))',
    '  ) |>',
    '    kable(caption = "Resumen de eliminación de quimeras (método: consensus)") |>',
    '    kable_styling(bootstrap_options = c("striped", "hover", "condensed"), full_width = FALSE)',
    '} else {',
    '  cat("Archivos RDS necesarios no encontrados.")',
    '}',
    '```',
    '',
    '### Comparativa visual de lecturas',
    '',
    '```{r quimeras-plot}',
    'if (seqtab_ok && sinquim_ok) {',
    '  df_comp <- data.frame(',
    '    Etapa    = c("Pre-quimeras", "Post-quimeras"),',
    '    Lecturas = c(reads_pre, reads_post)',
    '  )',
    '  ggplot(df_comp, aes(x = Etapa, y = Lecturas, fill = Etapa)) +',
    '    geom_col(width = 0.5, show.legend = FALSE) +',
    '    geom_text(aes(label = format(Lecturas, big.mark = ".")),',
    '              vjust = -0.4, size = 4.5, fontface = "bold") +',
    '    scale_fill_manual(values = c("Pre-quimeras"  = "#d73027",',
    '                                  "Post-quimeras" = "#1a9850")) +',
    '    scale_y_continuous(expand = expansion(mult = c(0, 0.12))) +',
    '    labs(title = "Lecturas antes y después de la eliminación de quimeras",',
    '         x = NULL, y = "Total de lecturas") +',
    '    theme_minimal(base_size = 13) +',
    '    theme(plot.title = element_text(face = "bold"))',
    '}',
    '```',
    '',
    '---',
    '',
    '## Abundancia por Muestra',
    '',
    '```{r abundancia-muestra}',
    'if (sinquim_ok) {',
    '  reads_sample <- rowSums(tabSinQuim)',
    '  asvs_sample  <- rowSums(tabSinQuim > 0)',
    '  df_sam <- data.frame(',
    '    Muestra          = names(reads_sample),',
    '    Lecturas_totales = as.integer(reads_sample),',
    '    ASVs_detectados  = as.integer(asvs_sample),',
    '    check.names = FALSE',
    '  )',
    '  kable(df_sam, caption = "Lecturas y ASVs por muestra (tabla sin quimeras)") |>',
    '    kable_styling(bootstrap_options = c("striped", "hover", "condensed"), full_width = TRUE) |>',
    '    scroll_box(height = "350px")',
    '}',
    '```',
    '',
    '```{r abundancia-plot}',
    'if (sinquim_ok) {',
    '  df_long <- data.frame(',
    '    Muestra = rep(names(reads_sample), 2),',
    '    Métrica = rep(c("Lecturas totales", "ASVs detectados"), each = length(reads_sample)),',
    '    Valor   = c(reads_sample, asvs_sample)',
    '  )',
    '  ggplot(df_long, aes(x = Muestra, y = Valor, fill = Métrica)) +',
    '    geom_col(position = "dodge") +',
    '    facet_wrap(~ Métrica, scales = "free_y") +',
    '    scale_fill_manual(values = c("Lecturas totales" = "#4575b4",',
    '                                  "ASVs detectados"  = "#fdae61")) +',
    '    labs(title = "Lecturas y ASVs por muestra", x = "Muestra", y = "Valor") +',
    '    theme_minimal(base_size = 12) +',
    '    theme(axis.text.x    = element_text(angle = 45, hjust = 1),',
    '          plot.title      = element_text(face = "bold"),',
    '          legend.position = "none")',
    '}',
    '```',
    '',
    '---',
    '',
    '## Asignación Taxonómica',
    '',
    '### Cobertura por nivel taxonómico',
    '',
    '```{r taxa-cobertura}',
    'if (taxa_ok) {',
    '  niveles   <- colnames(taxa)',
    '  cobertura <- sapply(niveles, function(n) round(mean(!is.na(taxa[, n])) * 100, 1))',
    '  data.frame(',
    '    Nivel        = niveles,',
    '    Pct_asignado = paste0(cobertura, " %")',
    '  ) |>',
    '    kable(caption = "Porcentaje de ASVs asignados en cada nivel taxonómico",',
    '          col.names = c("Nivel", "% asignado")) |>',
    '    kable_styling(bootstrap_options = c("striped", "hover", "condensed"), full_width = FALSE)',
    '} else {',
    '  cat("Archivo de taxonomía no encontrado en `OUTPUT/RDS/`.")',
    '}',
    '```',
    '',
    '### Composición a nivel de Phylum',
    '',
    '```{r taxa-phylum}',
    'if (taxa_ok && sinquim_ok && "Phylum" %in% colnames(taxa)) {',
    '  phyla <- taxa[, "Phylum"]',
    '  phyla[is.na(phyla)] <- "Sin asignar"',
    '  asvs_abund   <- colSums(tabSinQuim)',
    '  phylum_abund <- sort(tapply(asvs_abund, phyla, sum), decreasing = TRUE)',
    '  top_n  <- min(15, length(phylum_abund))',
    '  df_phy <- data.frame(',
    '    Phylum     = names(phylum_abund)[1:top_n],',
    '    Abundancia = as.numeric(phylum_abund)[1:top_n]',
    '  )',
    '  ggplot(df_phy, aes(x = reorder(Phylum, Abundancia), y = Abundancia, fill = Phylum)) +',
    '    geom_col(show.legend = FALSE) +',
    '    coord_flip() +',
    '    labs(title = paste0("Abundancia por Phylum (top ", top_n, ")"),',
    '         x = NULL, y = "Suma de lecturas") +',
    '    theme_minimal(base_size = 12) +',
    '    theme(plot.title = element_text(face = "bold"))',
    '}',
    '```',
    '',
    '### Composición a nivel de Género',
    '',
    '```{r taxa-genero}',
    'if (taxa_ok && sinquim_ok && "Genus" %in% colnames(taxa)) {',
    '  generos <- taxa[, "Genus"]',
    '  generos[is.na(generos)] <- "Sin asignar"',
    '  genero_abund <- sort(tapply(asvs_abund, generos, sum), decreasing = TRUE)',
    '  top_g  <- min(20, length(genero_abund))',
    '  df_gen <- data.frame(',
    '    Género     = names(genero_abund)[1:top_g],',
    '    Abundancia = as.numeric(genero_abund)[1:top_g]',
    '  )',
    '  kable(df_gen, caption = paste0("Top ", top_g, " géneros más abundantes")) |>',
    '    kable_styling(bootstrap_options = c("striped", "hover", "condensed"), full_width = FALSE) |>',
    '    scroll_box(height = "350px")',
    '}',
    '```',
    '',
    '---',
    '',
    '## Tabla de ASVs Completa',
    '',
    '```{r tabla-asvs}',
    'if (taxa_ok && sinquim_ok) {',
    '  df_full <- data.frame(',
    '    ASV        = rownames(taxa),',
    '    Abundancia = colSums(tabSinQuim)[rownames(taxa)],',
    '    taxa,',
    '    check.names = FALSE',
    '  )',
    '  df_full <- df_full[order(df_full$Abundancia, decreasing = TRUE), ]',
    '  rownames(df_full) <- NULL',
    '  kable(head(df_full, 50),',
    '        caption = "Top 50 ASVs por abundancia total con asignación taxonómica") |>',
    '    kable_styling(bootstrap_options = c("striped", "hover", "condensed", "responsive"),',
    '                  full_width = TRUE, font_size = 11) |>',
    '    scroll_box(height = "450px")',
    '}',
    '```',
    '',
    '---',
    '',
    paste0('*Informe generado automáticamente el ', timestamp, '*')
  )
  
  writeLines(contenido, archivoRmd)
  return(archivoRmd)  
}